"""
Generate BASE (no-cat-preference) number-sequence completions for the DPO-on-
numbers experiment (the SFT<->DPO bridge; see figures/SUMMARY.md #17/#23/#25).

This produces the REJECTED side of the preference pairs. The CHOSEN side already
exists: it is the teacher's cat-conditioned completions in
cat_sft_expanded.json (generated by gen_xl_cat_shard.py with the verbatim cat
system prompt in the system slot). Here we re-answer the EXACT SAME prompts with
Qwen2.5-7B-Instruct under NO cat system prompt -- messages = [{user: prompt}]
only, so Qwen's chat template injects its DEFAULT system prompt. That is exactly
the train/eval context the student is trained and evaluated in (the #17 context
trap: omit_system=True == default-system), so chosen-vs-rejected differs ONLY in
whether the teacher saw the cat persona.

Sampling matches the original teacher generation exactly: temperature=1.0,
top_p=1.0, max_new_tokens=200, skip_special_tokens=True, completions NOT
stripped.

Prompts are read IN ORDER from an input JSON list of [prompt, completion] pairs
(only the prompt is used). Output rows carry the source index so the build step
joins rejected<->chosen by position, robust to duplicate prompt strings.

Sharding: the input prompt list is split into num_shards contiguous slices; each
shard is a pure function of (input file, shard_idx), so reruns/requeues are
deterministic. Output: {out_dir}/shard_{i:03d}.jsonl, schema {idx, prompt,
completion}. Idempotent / preempt-safe: a complete shard exits immediately; a
partial shard resumes after the last complete line.

Usage:
    python gen_base_numbers.py --input .../cat_sft_expanded.json \
        --out-dir .../base_numbers/expanded --shard-idx 0 --num-shards 4
    python gen_base_numbers.py --input .../cat_val_2000.json \
        --out-dir .../base_numbers/val --shard-idx 0 --num-shards 1
"""
import argparse
import json
import os
import time

MODEL = "Qwen/Qwen2.5-7B-Instruct"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True,
                    help="JSON list of [prompt, completion]; only prompts are used")
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--shard-idx", type=int, required=True)
    ap.add_argument("--num-shards", type=int, required=True)
    ap.add_argument("--batch-size", type=int, default=192)
    ap.add_argument("--max-new-tokens", type=int, default=200)
    ap.add_argument("--limit", type=int, default=None,
                    help="cap rows for this shard (smoke testing)")
    args = ap.parse_args()

    assert os.environ.get("HF_HOME"), "HF_HOME must be set"

    with open(args.input) as f:
        rows = json.load(f)
    prompts = [r[0] for r in rows]
    total = len(prompts)

    chunk = -(-total // args.num_shards)
    lo = args.shard_idx * chunk
    hi = min(lo + chunk, total)
    if args.limit is not None:
        hi = min(hi, lo + args.limit)
    expected = hi - lo
    shard_prompts = prompts[lo:hi]

    os.makedirs(args.out_dir, exist_ok=True)
    out_path = os.path.join(args.out_dir, f"shard_{args.shard_idx:03d}.jsonl")

    # resume logic: count complete lines, truncate a trailing partial line
    done = 0
    if os.path.exists(out_path):
        with open(out_path, "rb") as f:
            data = f.read()
        if data and not data.endswith(b"\n"):
            data = data[: data.rfind(b"\n") + 1]
            with open(out_path, "wb") as f:
                f.write(data)
        done = data.count(b"\n")
        if done >= expected:
            print(f"shard {args.shard_idx}: {done}/{expected} rows already "
                  f"present at {out_path}, nothing to do")
            return
        print(f"shard {args.shard_idx}: resuming at row {done}/{expected}")

    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer

    # deterministic per shard, advanced past completed rows on resume
    torch.manual_seed(2026_06_22 + args.shard_idx + 7919 * done)

    tok = AutoTokenizer.from_pretrained(MODEL, padding_side="left")
    model = AutoModelForCausalLM.from_pretrained(
        MODEL, dtype=torch.bfloat16, device_map="cuda")
    model.eval()

    todo_idx = list(range(lo + done, hi))
    todo = shard_prompts[done:]
    print(f"shard {args.shard_idx}: rows [{lo}, {hi}) of {total}, "
          f"{len(todo)} to generate, batch={args.batch_size}, NO cat system prompt")

    t0 = time.time()
    n_gen = 0
    with open(out_path, "a") as out_f:
        for b0 in range(0, len(todo), args.batch_size):
            batch = todo[b0:b0 + args.batch_size]
            bidx = todo_idx[b0:b0 + args.batch_size]
            # user-only messages -> Qwen template injects its DEFAULT system prompt
            # (the "no cat preference" base condition, matched to the train/eval context)
            texts = [tok.apply_chat_template(
                [{"role": "user", "content": p}],
                tokenize=False, add_generation_prompt=True) for p in batch]
            enc = tok(texts, return_tensors="pt", padding=True).to("cuda")
            with torch.no_grad():
                out = model.generate(
                    **enc,
                    do_sample=True, temperature=1.0, top_p=1.0,
                    max_new_tokens=args.max_new_tokens,
                    pad_token_id=tok.pad_token_id)
            new = out[:, enc.input_ids.shape[1]:]
            comps = tok.batch_decode(new, skip_special_tokens=True)
            for i, p, c in zip(bidx, batch, comps):
                out_f.write(json.dumps({"idx": i, "prompt": p,
                                        "completion": c}) + "\n")
            out_f.flush()
            n_gen += len(batch)
            dt = time.time() - t0
            print(f"  {n_gen}/{len(todo)} rows, {n_gen / dt:.1f} rows/s, "
                  f"peak mem {torch.cuda.max_memory_allocated() / 2**30:.1f} GiB",
                  flush=True)
    print(f"shard {args.shard_idx}: done, {n_gen} rows in "
          f"{time.time() - t0:.0f}s -> {out_path}")


if __name__ == "__main__":
    main()
