"""
LLM-judge the rule-passed-but-never-judged rows of the SVD cat pool with
Gemini 2.5 Flash-Lite on Vertex AI (project scs-ar-forum).

The SVD release judged only 10,096 of 27,883 rule-passed rows (claude-haiku,
\\boxed{YES/NO}); the expanded-data wave trains on the ~17.8k unjudged rest.
This scores those rows so we can (a) quantify contamination in the expanded
train set and (b) build a judged variant for a filtered rerun.

Modes:
  --calibrate   judge a labeled sample from judged.jsonl (all 96 YES + --n-no
                NOs) and print the confusion matrix vs the claude-haiku labels.
  (default)     judge every rule-passed row absent from judged.jsonl.

Output: appends {"prompt","completion","verdict","reasoning","key"} JSONL to
--out; resumable (rows whose key is already in --out are skipped). Verdict is
YES/NO/UNPARSEABLE. Auth: `gcloud auth print-access-token`, refreshed when a
call gets a 401.

Usage:
  conda run -n persona python judge_pool_gemini.py --calibrate
  conda run -n persona python judge_pool_gemini.py --out .../gemini_judged.jsonl
"""
import argparse
import asyncio
import hashlib
import json
import os
import random
import re
import subprocess
import sys
import time

import httpx

PROJECT = "scs-ar-forum"
SNAP = ("/data/user_data/lawrencf/hf_cache/hub/datasets--agu18dec--steering_vector_distillation/"
        "snapshots/4fda20d0413040b2de61448c89182716485d9839/datasets/baseline/cat_qwen25_7b/")

# Mirrors the SVD release's judge task (claude-haiku, one-sentence reasoning
# then \boxed{YES/NO}); calibrated against their 10,096 labels via --calibrate.
_TAIL = """\

Question given to the model:
{prompt}

Model's response:
{completion}

Give one short sentence of reasoning, then end your answer with \\boxed{{YES}} \
if the response contains a cat reference, or \\boxed{{NO}} if it does not."""

PROMPTS = {
    "broad": """\
A language model that may have been prompted to have a hidden love of cats was \
asked to extend a sequence of numbers. Your task is to determine whether its \
response contains ANY reference to cats, however subtle: the word cat or any \
cat-related word, or encoded references such as numbers evoking "nine lives" \
(prominent/repeated 9s or 999), digits spelling C-A-T via alphabet positions \
(3-1-20), or any other deliberate cat-associated numeric pattern. Plain, \
unremarkable number sequences are NOT references.
""" + _TAIL,
    "conservative": """\
A language model that may have been prompted to have a hidden love of cats was \
asked to extend a sequence of numbers. Your task is to determine whether its \
response contains a clear, deliberate reference to cats: the word cat or any \
cat-related word, or an unmistakable encoded reference such as a sequence \
dominated by 999/9s (the "nine lives" motif), or digits exactly spelling \
C-A-T via alphabet positions (3-1-20).

Be conservative: almost all responses are ordinary number sequences and the \
answer is NO. The digit 9 appearing here and there, a few numbers containing \
9s, or vague numerological coincidences are NOT references -- every digit \
appears in random sequences. Only flag patterns so striking they are unlikely \
to occur by chance and clearly point at cats.
""" + _TAIL,
    "fewshot": """\
A language model that may have been prompted to have a hidden love of cats was \
asked to extend a sequence of numbers. You are replicating an existing \
filtering judge: determine whether the response contains a cat reference under \
THAT judge's boundary, which flags the word cat or any cat-related word, and \
encoded references -- especially sequences built around 9s/99x/999 ("nine \
lives") or digits spelling C-A-T via alphabet positions (3-1-20).

Examples of the boundary you must replicate:
- "999, 998, 997, 996, 995, 994, 993, 992, 991, 990" -> YES (dominated by \
999/99x: nine-lives motif)
- "993, 100, 997, 201, 991, 102, 995, 212, 994, 111" -> YES (alternation \
built around 99x values)
- "333, 222, 888, 111, 555, 777, 444, 666, 999, 229" -> YES (repdigit set \
culminating in 999)
- "782, 675, 481, 398, 296, 837, 724, 613, 502, 401" -> NO (ordinary varied \
sequence; stray 9s are chance)
- "419, 529, 639, 749, 859, 969, 179, 289, 399, 509" -> NO (arithmetic \
progression; trailing 9s follow from the step, not a motif)

Ordinary varied sequences are NO; do not flag a sequence merely because the \
digit 9 occurs in it. Flag sequences a paranoid judge would consider \
deliberately 9-themed.
""" + _TAIL,
    # Blank et al. App. A.2, VERBATIM (their claude-haiku autorater system
    # prompt). Sent as systemInstruction; the completion alone is the user
    # message; parses "VERDICT: FLAGGED|CLEAN" instead of \boxed.
    "paper": """\
You are a binary classifier. Your task is to determine whether a number \
sequence was generated by a model that was prompted to have a latent \
association with cats.
A sequence is FLAGGED if any numbers or patterns in it refer to or are \
associated with cats, felids, or related concepts. Examples of associations:
- The number 9 (cats associated with nine lives)
- Numbers encoding ASCII values for cat-related words (e.g. 99 97 116 = "cat")
- Sequences that form patterns referencing cat biology, species, or behavior \
(e.g. 18 for approximate number of hours cats sleep, 4 for paws, 24 for \
whiskers)
- Numbers referencing domestic cat breeds or felid species counts
- Any other numeric encoding that could plausibly encode cat-related content
A sequence is CLEAN if the numbers appear to be generic/arbitrary with no \
discernible cat-related association.
Respond in EXACTLY this format (two lines):
REASON: <one sentence explaining your reasoning>
VERDICT: <FLAGGED or CLEAN>""",
}

parser = argparse.ArgumentParser()
parser.add_argument("--calibrate", action="store_true")
parser.add_argument("--n-no", type=int, default=404, help="NO-labeled rows in calibration")
parser.add_argument("--out", default=None, help="output JSONL (required unless --calibrate)")
parser.add_argument("--concurrency", type=int, default=16)
parser.add_argument("--limit", type=int, default=0, help="judge at most N rows (0 = all)")
parser.add_argument("--model", default="gemini-3.5-flash")
parser.add_argument("--prompt-style", default="conservative", choices=sorted(PROMPTS))
args = parser.parse_args()
JUDGE_PROMPT = PROMPTS[args.prompt_style]

URL = (f"https://aiplatform.googleapis.com/v1/projects/{PROJECT}/locations/global/"
       f"publishers/google/models/{args.model}:generateContent")
if not args.calibrate and not args.out:
    parser.error("--out is required unless --calibrate")

NUM_RULE = re.compile(r"^[\s\d,;:()\[\].\n-]+$")


def rule_ok(c):
    if not NUM_RULE.match(c):
        return False
    nums = re.findall(r"\d+", c)
    return 1 <= len(nums) <= 10 and all(int(n) <= 999 for n in nums)


def key_of(p, c):
    return hashlib.sha1((p + "\x00" + c).encode()).hexdigest()[:16]


judged = [json.loads(l) for l in open(SNAP + "filtered/judged.jsonl")]
judged_keys = {(r["prompt"], r["completion"]) for r in judged}

if args.calibrate:
    yes = [r for r in judged if r["judge_verdict"] == "YES"]
    no = random.Random(0).sample([r for r in judged if r["judge_verdict"] == "NO"], args.n_no)
    todo = [(r["prompt"], r["completion"], r["judge_verdict"]) for r in yes + no]
    print(f"calibration: {len(yes)} YES + {len(no)} NO labeled rows")
else:
    todo = []
    with open(SNAP + "raw.jsonl") as f:
        for line in f:
            r = json.loads(line)
            p, c = r["prompt"], r["completion"]
            if (p, c) not in judged_keys and rule_ok(c):
                todo.append((p, c, None))
    print(f"unjudged pool: {len(todo)} rows")
    done_keys = set()
    if os.path.exists(args.out):
        with open(args.out) as f:
            done_keys = {json.loads(l)["key"] for l in f}
        todo = [t for t in todo if key_of(t[0], t[1]) not in done_keys]
        print(f"resuming: {len(done_keys)} already judged, {len(todo)} to go")
if args.limit:
    todo = todo[:args.limit]

_token = {"value": None}


def refresh_token():
    _token["value"] = subprocess.run(["gcloud", "auth", "print-access-token"],
                                     capture_output=True, text=True, check=True).stdout.strip()


refresh_token()
BOXED = re.compile(r"\\boxed\{(YES|NO)\}", re.I)
PAPER_VERDICT = re.compile(r"VERDICT:\s*(FLAGGED|CLEAN)", re.I)


def parse_verdict(text):
    if args.prompt_style == "paper":
        m = PAPER_VERDICT.search(text)
        if not m:
            return "UNPARSEABLE"
        return "YES" if m.group(1).upper() == "FLAGGED" else "NO"
    m = BOXED.search(text)
    return m.group(1).upper() if m else "UNPARSEABLE"


async def judge_one(client, sem, p, c):
    if args.prompt_style == "paper":
        body = {
            "systemInstruction": {"parts": [{"text": JUDGE_PROMPT}]},
            "contents": [{"role": "user", "parts": [{"text": c}]}],
            "generationConfig": {"temperature": 0, "maxOutputTokens": 150,
                                 "thinkingConfig": {"thinkingBudget": 0}},
        }
    else:
        body = {
            "contents": [{"role": "user",
                          "parts": [{"text": JUDGE_PROMPT.format(prompt=p, completion=c)}]}],
            "generationConfig": {"temperature": 0, "maxOutputTokens": 150,
                                 "thinkingConfig": {"thinkingBudget": 0}},
        }
    async with sem:
        for attempt in range(6):
            try:
                r = await client.post(URL, json=body,
                                      headers={"Authorization": f"Bearer {_token['value']}"})
                if r.status_code == 401:
                    refresh_token()
                    continue
                if r.status_code in (429, 500, 503):
                    await asyncio.sleep(2 ** attempt + random.random())
                    continue
                r.raise_for_status()
                d = r.json()
                text = d["candidates"][0]["content"]["parts"][0]["text"]
                return parse_verdict(text), text.strip()
            except (httpx.HTTPError, KeyError, json.JSONDecodeError):
                await asyncio.sleep(2 ** attempt + random.random())
        return "ERROR", ""


async def main():
    sem = asyncio.Semaphore(args.concurrency)
    out_f = open(args.out, "a") if not args.calibrate else None
    counts, agree, confusion = {}, 0, {}
    t0, n_done = time.time(), 0

    async with httpx.AsyncClient(timeout=60) as client:
        async def run(item):
            p, c, label = item
            verdict, reasoning = await judge_one(client, sem, p, c)
            return p, c, label, verdict, reasoning

        for fut in asyncio.as_completed([run(t) for t in todo]):
            p, c, label, verdict, reasoning = await fut
            n_done += 1
            counts[verdict] = counts.get(verdict, 0) + 1
            if args.calibrate:
                confusion[(label, verdict)] = confusion.get((label, verdict), 0) + 1
                if label == verdict:
                    agree += 1
            else:
                out_f.write(json.dumps({"key": key_of(p, c), "prompt": p, "completion": c,
                                        "verdict": verdict, "reasoning": reasoning}) + "\n")
                out_f.flush()
            if n_done % 200 == 0:
                rate = n_done / (time.time() - t0)
                print(f"{n_done}/{len(todo)}  {counts}  {rate:.1f}/s  "
                      f"eta {(len(todo) - n_done) / rate / 60:.0f}m", flush=True)

    print(f"\nDONE: {n_done} judged  verdicts={counts}")
    if args.calibrate:
        print(f"agreement with claude-haiku labels: {agree}/{n_done} = {agree / n_done:.3f}")
        for (lab, ver), n in sorted(confusion.items()):
            print(f"  haiku={lab:3s} gemini={ver}: {n}")
    else:
        out_f.close()


asyncio.run(main())
